config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :studios
    resources :bookings
  end

  resources :studios do
    resources :rooms
  end

  resources :rooms do
    resources :bookings
    resources :items
  end

  resources :bookings do
    resources :reviews
    resources :messages, only: :create
    resources :jams
  end

  resources :chatrooms, only: :show

  resources :jams
  resources :jams_users

  resources :jams do
    resources :jams_users
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :review, dependent: :destroy
  belongs_to :jam, optional: true, dependent: :destroy
  belongs_to :user
  belongs_to :room
  has_many :messages, dependent: :destroy
  validates :date, presence: true
  validates :time, presence: true

  def formatted_date
    Date.strptime(date, "%Y-%d-%m")
  end
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :show, :index]

  def new
    @room = Room.find(params[:room_id])
    @booking = Booking.new
    @date = params[:format].to_date
    @datearray = []

    month = @date.month
    year = @date.year
    @start = Date.new(year, month, 1)
    30.times do
      @datearray << @start
      @start = @start + 1
    end
    @start = Date.new(year, month, 1)

    @timearray = [ "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" ]
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    @room = Room.find(params[:room_id])
    @booking.room = @room
    @user = current_user
    @booking.user = @user
    @booking.starts_at = DateTime.parse("#{@booking.date} #{@booking.time}")
    if @booking.save
      if params[:other]
        @jam = Jam.find(params[:other][:jam_id])
        @jam.booking = @booking
        @jam.save
        redirect_to jam_path(@jam) and return
      end
      redirect_to booking_path(@booking) and return
    else
      redirect_to new_room_booking_path(@room, Date.today)
    end

  end

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new
    @id = @booking.room.studio.id
    @studios = Studio.where(id: @id)
    @studio = Studio.find(@id)
    @markers = [
      {
        lat: @studio.latitude,
        lng: @studio.longitude,
      }]
    @message = Message.new
  end

  def destroy
    @jam = Jam.find(params[:id])
    @jam.destroy
    redirect_to jams_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time)
  end
end

app/views/bookings/new.html.erb
<br>
<br>
<div class="row">
<br>
<div class= "col-4">
<h2 class="monthtitle">Votre salle</h2>
        <div class="card-room">
          <%= link_to room_path(@room) do  %>
             <%= cl_image_tag @room.photo.key, class: "card-studio-img" %>
          <% end %>
          <div class="card-room-infos">
            <div class="studio-name">
             <p><%= @room.studio.name %></p>
            </div>
            <div class="card-room-description">
              <h2><%= link_to @room.name, room_path(@room) %></h2>
              <p class="address"><%= @room.studio.address %></p>
              <p class="description mt-2"><%= @room.description %></p>
              <p class="mt-2 capacity">  Capacité max : <%= @room.capacity %> </p>
            </div>
            <div class="card-room-gears d-flex mt-2">
              <div class="d-flex">
                Matériel
                <a class="ml-2" data-toggle="collapse" href="#collapseExample-<%=@room.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
                  <i class="fas fa-plus"></i>
                </a>
              </div>
            </div>
            <div class="collapse" id="collapseExample-<%=@room.id%>">
              <% @room.items.each do |item| %>
                <p>- <%= item.name %></p>
              <% end %>
            </div>
          </div>
        </div>
   </div>



  <div class="col-4">
  <div class="bookcard">
    <h2 class="monthtitle">Choisir un jour</h2>
    <br>
  <div class="d-flex">
    <div class="monthdir"><%= link_to "<", new_room_booking_path(@room, @date - 30) %></div>
    <div class="monthbox"><h4><%=Date::MONTHNAMES[@date.month]%></h4></div>
    <div class="monthdir"><%= link_to ">", new_room_booking_path(@room, @date + 30) %></div>
  </div>
  <br>
  <div class="d-flex">
    <div class="daybox">L</div>
    <div class="daybox">M</div>
    <div class="daybox">M</div>
    <div class="daybox">J</div>
    <div class="daybox">V</div>
    <div class="daybox">S</div>
    <div class="daybox">D</div>
  </div>
  <div class="d-flex flex-wrap">
  <% if @start.wday == 0 %>
  <% 6.times do %>
    <div class="datebox text-center" id=""></div>
  <% end %>
    <%else%>
  <% (@start.wday - 1).times do %>
    <div class="datebox text-center" id=""></div>
  <% end %>
  <% end %>
  <% @datearray.each do |date| %>
    <% if @date == date %>
      <div class="datebox text-center red" id="<%date%>"><%=date.day%></div>
    <% else %>
      <div class="datebox text-center" id="<%date%>"><%= link_to date.day, new_room_booking_path(@room, date) %></div>
    <% end %>
  <%end%>
  </div>
  </div>
</div>

  <div class="col-4">
  <h2 class="monthtitle">Choisir une heure</h2>
  <% @timearray.each do |time| %>
    <% if @date < Date.today || (@date - Date.today).to_i > 14 %>
      <div class="text-center booked">-</div>
    <% elsif Booking.where(date: @date.to_s, time: time).length > 0 %>
      <div class="text-center booked">Réservé</div>
    <% else %>
      <div class="text-center timebox" id= ""><%=time%></div>
    <% end %>
  <%end%>
  </div>


</div>

<div class="d-flex justify-content-center">

  <%= simple_form_for [ @room, @booking ] do |f| %>
  <%= f.input :date, as: :string, input_html: { value: params[:format] }, as: :hidden %>
  <%= f.input :time, as: :string, as: :hidden %>
  <%= f.input :starts_at, as: :DateTime, as: :hidden %>
  <%= f.submit "Réserver", class: 'btn btn-primary book-btn mb-4' %>
  <% end %>

</div>

</div>

app/views/bookings/show.html.erb
<br>
<br>
<div class="d-flex flex-wrap">
  <div class="col-3">
    <h3>Votre salle</h3>
    <br>
    <div class="card-room mb-3">
      <%= link_to room_path(@booking.room) do  %>
          <%= cl_image_tag @booking.room.photo.key, class: "card-studio-img" %>
      <% end %>
      <div class="card-room-infos">
        <div class="studio-name">
         <p><%= @booking.room.studio.name %></p>
        </div>
        <div class="card-room-description">
          <h2><%= link_to @booking.room.name, room_path(@booking.room) %></h2>
          <p class="description mt-2"><%= @booking.room.description %></p>
          <p class="mt-2 capacity">  Capacité max : <%= @booking.room.capacity %> </p>
        </div>
        <div class="card-room-gears d-flex mt-2">
          <div class="d-flex">
            Matériel
            <a class="ml-2" data-toggle="collapse" href="#collapseExample-<%=@booking.room.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
              <i class="fas fa-plus"></i>
            </a>
          </div>
        </div>
        <div class="collapse" id="collapseExample-<%=@booking.room.id%>">
          <% @booking.room.items.each do |item| %>
            <p>- <%= item.name %></p>
          <% end %>
        </div>
      </div>
    </div>
    <br>

  </div>

<div class="col-6">
  <h3>Détails de la réservation</h3>
  <br>
  <div class="row booking-card">
    <div class="col-4 text-center d-flex flex-column align-items-center booking-card-infos">
        <div class="dflex mb-1 calendar-book-infos">
          <h5>
            <i class="far fa-calendar"></i>
            <br>
            <%= I18n.l(@booking.starts_at.to_date, :format => :long) %>
          </h5>
        </div>
        <div class="d-flex">
          <h5>
            <p><i class="far fa-clock"></i>
              <br>
            <%= @booking.time %></p>
          </h5>
        </div>
    </div>
    <div class="col-8 book-details">
      <div class="">
      <p><strong>Nom:</strong> <%= @booking.user.first_name %> <%= @booking.user.last_name %></p>
        <p><strong>Statut : </strong>
        <% if Date.today > @booking.date.to_date %>
          réalisée</p>
        <% elsif Date.today <= @booking.date.to_date %>
          confirmée</p>
        <% end %>
      <p><strong>Paiement</strong> reçu le <%=I18n.l(Date.today, :format => :default)%> <br> Mastercard **** **** **** 2345</p>
      </div>
    </div>
  </div>
  <br>
<!--   <div class="row mr-2 ml-2">
    <div class="col-12"> -->

        <% if Jam.where(booking_id: @booking.id).count == 1 %>
        <div class="jam-users-book">
<h3>Musiciens</h3>
<div class="d-flex justify-content-start">
    <% Jam.where(booking_id: @booking.id)[0].jams_users.each do |jam_user| %>
  
      <div class="jam-user">
      <div class="jam-user-photo">
      <% if jam_user.user.photo.attached? %>
          <%= cl_image_tag jam_user.user.photo.key, class: "card-jam-photo-small" %>
          <% else %>
          <%= image_tag "https://media.vogue.fr/photos/5c2f43509662b10dc0b3ffc5/master/pass/sub_david_bowie_8714.jpeg", class: "card-jam-photo-small" %>
          <% end %>
      </div>
      <div class="jam-user-name">
        <strong>
          <%= jam_user.user.first_name %>
          <%= jam_user.user.last_name %>
        </strong>
      </div>
      <div class="jam-user-instrument">

        <% if asset_exist?("#{jam_user.instrument.downcase}.png") %>
          <%= image_tag "#{jam_user.instrument.downcase}.png", class: "jam-instrument-img" %>
        <% else %>
          <%= jam_user.instrument.capitalize %>
        <% end %>
      </div>
    </div>
  
    <% end %>
          </div>
</div>
    <% end %>


      <div class="your-review">
        <% if @booking.user == current_user %>
          <% if Date.today <= @booking.date.to_date %>
            <p><strong><%=@studio.name  %> - </strong><%= @booking.room.studio.address %></p>
              <div class="book-map">
                <div id="map"
                  style="width: 100%; height: 161px; position: relative;"
                  data-markers="<%= @markers.to_json %>"
                  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
                  data-current-position="<%= @current_position.to_json %>"
                  data-current-user="<%=current_user.first_name.chars.first.upcase%><%=current_user.last_name.chars.first.upcase%>">
                </div>
              </div>
          <% else %>
            <% if @booking.review.present? %>
              <br>
              <br>
              <h4> Votre avis :</h4>
              <p><%= @booking.review.content %> </p>
            <% else %>
              <div class="booking-card-review">
                <%= simple_form_for [@booking, @review] do |f| %>
                  <div class="first-line-review">
                    <h5>Etes-vous satisfait de l'expérience?</h5>
                      <div class="stars-rating">
                        <%= f.input :rating, as: :hidden %>
                        <% 5.times do |index| %>
                        <i id="<%= index + 1 %>" class="review-rating far fa-star"></i>
                        <% end %>
                      </div>
                  </div>
                  <div class="d-flex justify-content-between">
                    <div class="review_title_container">
                      <%= f.input :title, label: "Titre", class: "title-input" %>
                    </div>
                  </div>
                  <div class="d-flex">
                    <div class="review_comment_container">
                      <%= f.input :content, as: :text, label: "Commentaire" %>
                    </div>
                    <div class="review_validation_button">
                      <%= f.submit "Valider", class: "btn btn-primary" %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <% if Date.today <= @booking.date.to_date %>
            <h5>Profil de <%= @booking.user.first_name%></h5>
            <ul>
              <li><%= @booking.user.first_name%></li>
              <li><%= @booking.user.last_name%></li>
              <li><%= @booking.user.nickname%></li>
              <li><%= @booking.user.email%></li>
            </ul>
          <% else %>
            <% if @booking.review.present? %>
              <h4>Avis de <%= @booking.user.first_name%> :</h4>
              <p><%= @booking.review.content  %> </p>
            <% else %>
              <h5><%= @booking.user.first_name%> n'a pas encore donné son avis</h5>
            <% end %>
          <% end %>
        <% end %>
      </div>
  <br>
</div>
<!-- /*
*
* ==========================================
* Message
* ==========================================
*
*/ -->
<div class="col-3">
  <h3 class="color-text-title-messages">Messages</h3>
  <br>
  <div class = "card-message">
    <div class="message-box">
      <div id="messages" data-booking-id="<%= @booking.id %>" data-user-id="<%= current_user.id %> ">
        <div class="welcoming-message">
          <% if @booking.messages == [] %>
            <p> Des questions à propos de votre réservation ?</p>
          <% end %>
        </div>
        <% @booking.messages.each do |message| %>
          <% flex_direction = (message.user == current_user ? "flex-row-reverse" : "flex-row")%>
          <div class="message-container d-flex w-100 <%= flex_direction %>">
            <% background = (message.user == current_user ? "m-sender" : "m-receiver")%>
            <div class="message-block <%= background %>">
              <div class="message-user-nickname">
                <i class="author-message">
                <span><%= message.user.first_name %> <%= message.user.last_name %></span>
                </i>
              </div>
              <div class="message-content" id="message-<%= message.id %>">
                <span><%= message.content %></span>
              </div>
              <div class="message-date">
                <i class="author-message">
                  <small><%= I18n.l(message.created_at, :format => :long) %></small>
                </i>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="add-messages">
      <%= simple_form_for [ @booking, @message ], remote: true do |f| %>
        <%= f.input :content, input_html: { class: "message-input"}, label: false, placeholder: "Votre message" %>
      <% end %>
    </div>
  </div>
</div>
</div>