config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :studios
    resources :bookings
  end

  resources :studios do
    resources :rooms
  end

  resources :rooms do
    resources :bookings
    resources :items
  end

  resources :bookings do
    resources :reviews
    resources :messages, only: :create
    resources :jams
  end

  resources :chatrooms, only: :show

  resources :jams
  resources :jams_users

  resources :jams do
    resources :jams_users
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © 2020 Musicnow, Inc. All rights reserved
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-music-now">
  <%= link_to root_path , class: "navbar-brand" do %>
    <h1 class="music-now"> MUSICNOW </h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item underlineHover <%= 'selectedItem' if controller.controller_name == 'studios' %>">
          <%= link_to "NOS STUDIOS", studios_path, id: "navbar-btn", class: "nav-link" %>
        </li>
        <li class="nav-item underlineHover <%= 'selectedItem' if controller.controller_name == 'rooms' %>">
          <%= link_to "NOS SALLES", rooms_path, id: "navbar-btn", class: "nav-link", data: { turbolinks: "false" } %>
        </li>
        <li class="nav-item underlineHover <%= 'selectedItem' if controller.controller_name == 'jams' %>">
          <%= link_to "JAM SESSION", jams_path, id: "navbar-btn", class: "nav-link",  data: { turbolinks: "false" } %>
        </li>

      <% if user_signed_in? %>
        <li class="nav-item underlineHover <%= 'selectedItem' if controller.controller_name == 'users' %>">
          <%= link_to "MON ESPACE", user_path(current_user), id: "navbar-btn", class: "nav-link" %>

        </li>
        <li class="nav-item dropdown ">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <%= image_tag "https://media.vogue.fr/photos/5c2f43509662b10dc0b3ffc5/master/pass/sub_david_bowie_8714.jpeg", class: "avatar dropdown-toggle ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "LOGIN", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>