config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :studios
    resources :bookings
  end

  resources :studios do
    resources :rooms
  end

  resources :rooms do
    resources :bookings
    resources :items
  end

  resources :bookings do
    resources :reviews
    resources :messages, only: :create
    resources :jams
  end

  resources :chatrooms, only: :show

  resources :jams
  resources :jams_users

  resources :jams do
    resources :jams_users
  end
end

app/models/jam.rb
class Jam < ApplicationRecord
  belongs_to :room, optional: true
  belongs_to :booking, optional: true
  has_many :users, through: :jams_users
  has_many :jams_users, dependent: :destroy
  has_one_attached :photo
  accepts_nested_attributes_for :jams_users
end

app/controllers/jams_controller.rb
class JamsController < ApplicationController
    def index
        @jams = Jam.all
        @userarray = {}
        @jams.each do |jam|
            jam.jams_users.each do |j|
                @userarray["#{j.jam.id} et #{j.user.id}".to_sym] = 1
            end
        end
        @myjams = []
        @jams.each do |jam|
            if @userarray["#{jam.id} et #{current_user.id}".to_sym] == 1 && jam.booking == nil
                @myjams << jam
            end
        end
    end

    def new
        @jam = Jam.new
        @jams_user = JamsUser.new

        @date = params[:format].to_date
        @datearray = []
        month = @date.month
        year = @date.year
        @start = Date.new(year, month, 1)
        30.times do
          @datearray << @start
          @start = @start + 1
        end
        @start = Date.new(year, month, 1)
        @timearray = [ "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" ]
    end

    def create
        @jam = Jam.new(jam_params)
        @jam.groupe = false
        @jams_user = JamsUser.new(instrument: params[:other][:instrument], admin: true, paid: false)
        @jams_user.user = current_user
        if @jam.save!
            @jams_user.jam = @jam
            @jams_user.save
            redirect_to jam_path(@jam)
        else
          raise
        end
    end

    def show
        @jam = Jam.find(params[:id])
        @jams_users = JamsUser.where(jam_id: @jam.id)
        @jams_user = JamsUser.new
        @rooms = Room.all.sample(4)
        @allpaid = 0
        @jams_users.each do |jams_user|
            if jams_user.paid == true
                @allpaid += 1
            end
        end
        @booking = Booking.new

        @date = @jam.date.to_date
        @datearray = []
        month = @date.month
        year = @date.year
        @start = Date.new(year, month, 1)
        30.times do
          @datearray << @start
          @start = @start + 1
        end
        @start = Date.new(year, month, 1)
        @jampresent = 0
        @jams_users.each do |j|
            if j.user == current_user
                @jampresent = 1
            end
        end
        @users = []
        @jams_users.each do |j|
            @users << j.user
        end
    end

    def update
        @jam = Jam.find(params[:id])
        @jams_users = JamsUser.where(jam_id: @jam.id)


        if @jam.groupe == true
            if @jam.update!(room_update_params)
                @jams_users.each do |jams_user|
                    jams_user.priceuser = (@jam.room.price / @jams_users.count).to_f
                end
                redirect_to jam_path(@jam)
            else
                raise
            end
        end

        if @jam.groupe == false
            if @jam.update!(update_params)
            redirect_to jam_path(@jam)
            else
            raise
            end
        end

    end

    def destroy
        @jam = Jam.find(params[:id])
        @jam.destroy
        redirect_to jams_path
      end

    private

    def jam_params
        params.require(:jam).permit(:name,:description,:date,:time,:photo)
    end

    def update_params
        params.require(:jam).permit(:name,:description,:groupe)
    end

    def room_update_params
        params.require(:jam).permit(:name,:description,:groupe, :room_id)
    end

end

app/views/jams/index.html.erb
<br>
<br>
<div class="row">

    <div class="col-3">
    <div class="sticky-top">
    <%= image_tag "https://blog.reverbnation.com/wp-content/uploads/2017/12/why-your-band-needs-to-practice-1500px.jpg", class: "jamimg" %>
    <br>
    <br>
    <h4>Trouver des jam sessions</h4>
    <h6>Vous cherchez des musiciens avec qui jouer? Trouvez ici des jam sessions ouvertes, inscrivez-vous, ou alors créez la votre!</h6>
    <br>
    <%= link_to "Créer ma jam", new_jam_path(Date.today), class:"btn btn-primary" %>
    </div>

    </div>

    <div class="col-9">
    <h4>Mes sessions</h4>
    <% @myjams.each do |jam| %>
        <div class="jamcard">
            <div class="row">
            <div class="col-4">
                <% if jam.photo.attached? %>
                <%= cl_image_tag jam.photo.key, class: "jam-hero-img" %>
                <% else %>
                <%= image_tag "https://blog.reverbnation.com/wp-content/uploads/2017/12/why-your-band-needs-to-practice-1500px.jpg", class: "jam-hero-img" %>
                <% end %>
            </div>
            <div class="col-8 float-left">
            <h5><%="#{jam.name}"%></h5>
            <div class="ownerjam">
            <h6><%="Créateur : #{jam.jams_users[0].user.first_name}"%></h6>
            </div>
            <div class="countjam">
            <h6>
                <%="Inscrits: #{jam.jams_users.count}"%>
                -
                <% jam.jams_users.each do |j| %>
                    <% if asset_exist?("#{j.instrument.downcase}.png") %>
                    <%= image_tag "#{j.instrument.downcase}.png", class: "jam-instrument-index" %>
                    <% else %>
                    <%= j.instrument.capitalize %>
                    <% end %>
                <% end %>
            </h6>
            </div>
            <div class="jam-desc">
            <% if jam.description.length > 200  %>
            <p><%="#{jam.description.first(200)}..."%></p>
            <% else %>
            <p><%="#{jam.description}"%></p>
            <% end %>
            </div>
                <div class="jamcalendar">
                <div class="row">
                <div class="jam-date"><i class="far fa-calendar"></i><%= " #{I18n.l(jam.date.to_date, :format => :long)}" %></div>
                <div class="jam-date"><i class="far fa-clock"></i><%=" #{jam.time}"%></div>
                </div>
                </div>
            <%= link_to "Voir cette jam", jam_path(jam), class:"btn btn-primary jam-btn" %></h5>
            </div>
            </div>
        </div>
    <% end %>

    <% if @myjams.length == 0 %>
    <div class="nojam">Vous n'avez pas encore de session!
    </div>
    <br>
    <% end %>

    <h4>Jam sessions ouvertes</h4>
    <% @jams.each do |jam| %>
    <% if jam.groupe == false && jam.jams_users[0].user != current_user && @myjams.include?(jam) == false %>
        <div class="jamcard">
            <div class="row">
                <div class="col-4">
                    <% if jam.photo.attached? %>
                    <%= cl_image_tag jam.photo.key, class: "jam-hero-img" %>
                    <% else %>
                    <%= image_tag "https://blog.reverbnation.com/wp-content/uploads/2017/12/why-your-band-needs-to-practice-1500px.jpg", class: "jam-hero-img" %>
                    <% end %>
                </div>
            <div class="col-8 float-left">
                <h5><%="#{jam.name}"%></h5>
                <div class="ownerjam">
                <h6><%="Créateur : #{jam.jams_users[0].user.first_name}"%></h6>
                </div>
                <div class="countjam">
                <h6>
                    <%="Inscrits: #{jam.jams_users.count}"%>
                    -
                    <% jam.jams_users.each do |j| %>
                    <% if asset_exist?("#{j.instrument.downcase}.png") %>
                    <%= image_tag "#{j.instrument.downcase}.png", class: "jam-instrument-index" %>
                    <% else %>
                    <%= j.instrument.capitalize %>
                    <% end %>
                    <% end %>
                </h6>
                </div>
                <div class="jam-desc">
                <% if jam.description.length > 200  %>
                <p><%="#{jam.description.first(200)}..."%></p>
                <% else %>
                <p><%="#{jam.description}"%></p>
                <% end %>
                </div>
                <div class="jamcalendar">
                <div class="row">
                <div class="jam-date"><i class="far fa-calendar"></i><%= " #{I18n.l(jam.date.to_date, :format => :long)}" %></div>
                <div class="jam-date"><i class="far fa-clock"></i><%=" #{jam.time}"%></div>
                </div>
                </div>
                <%= link_to "Rejoindre cette jam", jam_path(jam), class:"btn btn-primary jam-btn" %></h5>
                </div>
                </div>
        </div>
    <% end %>
    <% end %>
    </div>
</div>

app/views/jams/new.html.erb
<br>
<h3>Créez votre jam session et rencontrez des musiciens !</h3>
<br>

<div class="row">
<div class="col-4">
  <div class="bookcard">
    <h4 class="monthtitle">Choisir un jour</h4>
    <br>
  <div class="d-flex">
    <div class="monthdir"><%= link_to "<", new_jam_path(@date - 30) %></div>
    <div class="monthbox"><h4><%=I18n.l(@date.to_date, :format => :long).split(" ")[2].capitalize %></h4></div>
    <div class="monthdir"><%= link_to ">", new_jam_path(@date + 30) %></div>
  </div>
  <br>
  <div class="d-flex">
    <div class="daybox">L</div>
    <div class="daybox">M</div>
    <div class="daybox">M</div>
    <div class="daybox">J</div>
    <div class="daybox">V</div>
    <div class="daybox">S</div>
    <div class="daybox">D</div>
  </div>
  <div class="d-flex flex-wrap">
  <% if @start.wday == 0 %>
  <% 6.times do %>
    <div class="datebox text-center" id=""></div>
  <% end %>
    <%else%>
  <% (@start.wday - 1).times do %>
    <div class="datebox text-center" id=""></div>
  <% end %>
  <% end %>
  <% @datearray.each do |date| %>
    <% if @date == date %>
      <div class="datebox text-center red" id="<%date%>"><%=date.day%></div>
    <% else %>
      <div class="datebox text-center" id="<%date%>"><%= link_to date.day, new_jam_path(date) %></div>
    <% end %>
  <%end%>
  </div>
  </div>
</div>

  <div class="col-4">
  <h4 class="monthtitle">Choisir une heure</h4>
  <% @timearray.each do |time| %>
    <% if @date < Date.today || (@date - Date.today).to_i > 14 %>
      <div class="text-center booked">-</div>
    <% else %>
      <div class="text-center timebox" id= ""><%=time%></div>
    <% end %>
  <%end%>
  </div>

  <div class="col-4">
  <h4>Votre jam session</h4>
  <%= simple_form_for [ @jam ] do |f| %>
  <%= f.input :name, as: :string, label: "Nom de la jam" %>
  <%= f.input :description, as: :text, label: "Qu'est ce que vous voulez jouer ?" %>
  <%= f.input :date, as: :string, input_html: { value: params[:format] }, as: :hidden %>
  <%= f.input :time, as: :string, as: :hidden%>
  <%= f.input :photo, as: :file %>
  <%= simple_fields_for :other do |o| %>
    <%= o.input :instrument, as: :string, label: 'Quel instrument jouez vous ?' %>
  <% end %>
  <%= f.submit "Créer ma session", class: 'btn btn-primary book-btn' %>
  <% end %>
  </div>
  </div>

app/views/jams/show.html.erb
<div class="hero-studio">
  <% if @jam.photo.attached? %>
  <%= cl_image_tag @jam.photo.key, class: "hero-studio-img" %>
  <% else %>
  <%= image_tag "https://blog.reverbnation.com/wp-content/uploads/2017/12/why-your-band-needs-to-practice-1500px.jpg", class: "hero-studio-img" %>
  <% end %>
  <h1 class="hero-studio-title"> <%= "#{@jams_users[0].user.first_name}'s jam session" %></h1>
</div>


<div class="container">

<% if @jams_users[0].user == current_user %>
<% end %>

  <div class="row">
    <div class="col-4">
    <div class="sticky-top">
      <div class="card-jam">
          <% if @jams_users[0].user.photo.attached? %>
          <%= cl_image_tag @jams_users[0].user.photo.key, class: "card-jam-photo" %>
          <% else %>
          <%= image_tag "https://media.vogue.fr/photos/5c2f43509662b10dc0b3ffc5/master/pass/sub_david_bowie_8714.jpeg", class: "card-jam-photo" %>
          <% end %>
          <div class="card-jam-title">
            <h4><%="#{@jam.name} proposée par #{@jams_users[0].user.first_name}"%></h4>
          </div>
          <div class="card-jam-description">
            <%=@jam.description%>
          </div>
          <h4>Date</h4>
          <% I18n.default_locale = :fr %>
          <h6><%=I18n.l(Date.today, :format => :long).split(" ")[2].capitalize%></h6>
          <div class="d-flex ml-3">
              <div class="daybox-jam">L</div>
              <div class="daybox-jam">M</div>
              <div class="daybox-jam">M</div>
              <div class="daybox-jam">J</div>
              <div class="daybox-jam">V</div>
              <div class="daybox-jam">S</div>
              <div class="daybox-jam">D</div>
          </div>
          <div class="d-flex flex-wrap ml-3">
            <% if @start.wday == 0 %>
            <% 6.times do %>
              <div class="datebox-jam text-center" id=""></div>
            <% end %>
              <%else%>
            <% (@start.wday - 1).times do %>
              <div class="datebox-jam text-center" id=""></div>
            <% end %>
            <% end %>
            <% @datearray.each do |date| %>
              <% if @date == date %>
                <div class="datebox-jam text-center red" id="<%date%>"><%=date.day%></div>
              <% else %>
                <div class="datebox-jam text-center" id="<%date%>"><%=date.day%></div>
              <% end %>
            <%end%>
          </div>
      <h4>Heure <i class="far fa-clock"></i></h4>
      <h5><%=@jam.time %></h5>
      <br>
      <%= link_to "Supprimer cette jam", jam_path(@jam), method: :delete %>
      </div>
    </div>
      </div>

<div class="col-8">
<div class="jam-users">
<h4>Musiciens</h4>
<div class="d-flex justify-content-start">
  <% @jams_users.each do |jam_user| %>
    <div class="jam-user">
      <div class="jam-user-photo">
      <% if jam_user.user.photo.attached? %>
          <%= cl_image_tag jam_user.user.photo.key, class: "card-jam-photo-small" %>
          <% else %>
          <%= image_tag "https://media.vogue.fr/photos/5c2f43509662b10dc0b3ffc5/master/pass/sub_david_bowie_8714.jpeg", class: "card-jam-photo-small" %>
          <% end %>
      </div>
      <div class="jam-user-name">
        <strong>
          <%= jam_user.user.first_name %>
          <%= jam_user.user.last_name %>
        </strong>
            <% if jam_user.user == current_user %>
            <p>(vous)</p>
            <% end %>
      </div>
      <div class="jam-user-instrument">

        <% if asset_exist?("#{jam_user.instrument.downcase}.png") %>
          <%= image_tag "#{jam_user.instrument.downcase}.png", class: "jam-instrument-img" %>
        <% else %>
          <%= jam_user.instrument.capitalize %>
        <% end %>
      </div>
        <% if @jams_users[0].user == current_user && jam_user.user != current_user %>
        <%= link_to "Refuser", jams_user_path(jam_user), method: :delete %>
        <% end %>
    </div>
  <% end %>

  <% if @jams_users.count == 1 && @jams_users[0].user == current_user %>
    <div class="jam-user">
      En attente d'autres players :)
    </div>
  <% end %>

  <% if @jam.groupe == false && @jampresent == 0 %>
  <div class="jam-user">
  <h5>Ajoutez-vous à cette jam!</h5>
    <%= simple_form_for [ @jam, @jams_user ] do |f| %>
      <%= f.input :instrument, as: :string %>
      <%= f.submit "S'ajouter", class: 'btn btn-primary book-btn' %>
    <% end %>
  <% end %>
  </div>
</div>
<% if @jams_users[0].user != current_user && @jam.groupe == false && @users.include?(current_user) %>
<div class="float-right">En attente de validation du groupe par le créateur de la jam</div>
<% end %>







<% if @jams_users[0].user == current_user && @jam.groupe == false %>
<%= simple_form_for [ @jam ] do |f| %>
<%= f.input :groupe, as: :boolean, input_html: {value: true}, as: :hidden %>
<%= f.submit "Trouver une salle avec ce groupe", class: 'btn btn-primary book-btn float-right' %>
<% end %>
<% end %>

<% if @jams_users[0].user == current_user && @jam.groupe == true && @jam.room_id == nil %>
  <div class="jam-rooms">
  <div class="d-flex flex-wrap justify-content-between">
    <% @rooms.each do |room| %>

        <div class="card-room-jam">
          <div class= "card-room-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),)">
              <%if room.photo.attached? %>
                <%= cl_image_tag room.photo.key, class: "card-studio-img" %>
              <% else %>
                <div class="card-studio-img" style="background-image: url('http://www.studiobleu.com/wp-content/uploads/2015/06/20181221-INDIGO-02.jpg')">
                </div>
              <% end %>
          </div>
          <div class="card-room-infos">
            <div class="studio-name">
             <p><%= room.studio.name %></p>
            </div>
            <div class="card-room-description">
              <h2><%= room.name %></h2>
              <p class="address"><%= room.studio.address %></p>
              <p class="description mt-2"><%= room.description %></p>
              <p class="mt-2 capacity"><i class="fas fa-users"></i> <%= room.capacity %> </p>
            </div>
            <%= simple_form_for [ @jam ] do |f| %>
            <%= f.input :room_id, input_html: {value: room.id}, as: :hidden %>
            <%= f.submit "Choisir cette room", class: 'btn btn-primary book-btn' %>
            <% end %>
            <div class="card-room-gears d-flex mt-2">
              <div class="d-flex">
                Matériel
                <a class="ml-2" data-toggle="collapse" href="#collapseExample-<%=room.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
                  <i class="fas fa-plus"></i>
                </a>
              </div>
            </div>
           <div class="collapse" id="collapseExample-<%=room.id%>">
              <% room.items.each do |item| %>
                <p>- <%= item.name %></p>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
  </div>
<% end %>

<div class="row">
<% if  @jam.room_id != nil %>
<div class="col-6">
<div class="jam-rooms">
<h4>Votre salle</h4>
        <div class="card-room-jam-chosen">
          <div class= "card-room-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),)">
              <%if @jam.room.photo.attached? %>
                <%= cl_image_tag @jam.room.photo.key, class: "card-studio-img" %>
              <% else %>
                <div class="card-studio-img" style="background-image: url('http://www.studiobleu.com/wp-content/uploads/2015/06/20181221-INDIGO-02.jpg')">
                </div>
              <% end %>
          </div>
          <div class="card-room-infos">
            <div class="studio-name">
             <p><%= @jam.room.studio.name %></p>
            </div>
            <div class="card-room-description">
              <h2><%= @jam.room.name %></h2>
              <p class="address"><%= @jam.room.studio.address %></p>
              <p class="mt-2 capacity"><i class="fas fa-users"></i> <%= @jam.room.capacity %> </p>
            </div>
            <div class="card-room-gears d-flex mt-2">
              <div class="d-flex">
                <i class="fas fa-search"></i>
                <a class="ml-2" data-toggle="collapse" href="#collapseExample-<%=@jam.room.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
                  Matériel
                </a>
              </div>
            </div>
           <div class="collapse" id="collapseExample-<%=@jam.room.id%>">
              <% @jam.room.items.each do |item| %>
                <p>- <%= item.name %></p>
              <% end %>
            </div>
          </div>
        </div>
        </div>
        </div>
<% end %>


<% if @jam.groupe == true && @jam.room_id != nil %>
<div class="col-6">
<div class="jam-rooms-add">
<h4>Partagez l'addition!</h4>
<br>
  <% @jams_users.each do |jams_user| %>
    <div class="row">
    <div class="col-6">
    <strong> <%= jams_user.user.first_name %></strong>
    <h6>A payer:</h6>
    <%= "#{(@jam.room.price.to_f / @jams_users.count).to_f.round(2)} €" %>
    </div>
    <div class="col-6">
      <% if jams_user.user == current_user && jams_user.paid == false %>
          <%= simple_form_for [ jams_user ] do |f| %>
          <%= f.input :paid, input_html: {value: true}, as: :hidden %>
          <%= f.submit "Pay", class: 'btn btn-primary' %>
          <% end %>
      <% else %>
          <% if jams_user.paid %>
          <br>
          <i class="fas fa-check"></i><%= " Payé" %>
          <% else %>
          <br>
          <%= "En attente du paiement" %>
          <% end %>
      <% end %>
    </div>
    </div>
    <br>
  <% end %>
    </div>
    <% if @allpaid == @jams_users.count && @jam.booking_id == nil && @jams_users[0].user != current_user %>
<div class="float-right">En attente de confirmation par le créateur de la jam</div>
<% end %>
    </div>
<% end %>
</div>




<% if @allpaid == @jams_users.count && @jam.booking_id == nil && @jams_users[0].user == current_user %>
<div class="jam-rooms">
<%="C'est tout bon, il ne reste plus qu'à confirmer!"%>
  <%= simple_form_for [ @jam.room, @booking ] do |f| %>
  <%= f.input :date, as: :string, input_html: { value: @jam.date }, as: :hidden %>
  <%= f.input :time, as: :string, input_html: { value: @jam.time }, as: :hidden %>
  <%= simple_fields_for :other do |o| %>
    <%= o.input :jam_id, input_html: { value: @jam.id }, as: :hidden %>
  <% end %>
  <%= f.submit "Confirmer", class: 'btn btn-primary book-btn' %>
  <% end %>
</div>
<% end %>

<% if @jam.booking_id != nil %>
<div class="jam-rooms">
<h4><%= "Votre réservation est faite!" %></h4>
<%= link_to "Voir ma réservation", booking_path(@jam.booking) %>
<% end %>
</div>
</div>
</div>
</div>
</div>