config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    resources :studios
    resources :bookings
  end

  resources :studios do
    resources :rooms
  end

  resources :rooms do
    resources :bookings
    resources :items
  end

  resources :bookings do
    resources :reviews
    resources :messages, only: :create
    resources :jams
  end

  resources :chatrooms, only: :show

  resources :jams
  resources :jams_users

  resources :jams do
    resources :jams_users
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings, :dependent => :destroy
  has_many :items_rooms
  has_many :items, through: :items_rooms
  has_many :reviews, through: :bookings
  has_one_attached :photo
  belongs_to :studio


  include PgSearch::Model
  pg_search_scope :global_search,
                  associated_against: {
                  items: [:name]
                  },
                  using: {
                  tsearch: { prefix: true } }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @rooms = Room.all.order(capacity: :asc)
    if params[:search]
      if params[:search][:address].present?
        @studios = Studio.near(params[:search][:address], 10).map(&:id)
        @rooms = @rooms.where(studio_id: @studios)
      end
      if params[:search][:capacity].present?
        @rooms = @rooms.where("capacity >= #{params[:search][:capacity]}")
      end
      if params[:search][:item].present?
        @rooms = @rooms.global_search(params[:search][:item])
      end
    end
    @tags =
      params[:search].present? ? params[:search].values.select(&:present?) : []
  end

  private

  def room_params
    params.require(:room).permit(:capacity, :name)
  end
end

app/views/rooms/index.html.erb
<div class="d-flex m-0 mt-5">
  <div class="filter">
  <div class="sticky-top">
    <h5>Filtrer par :</h5>
    <div>
      <%= simple_form_for :search, url: rooms_path, method: :get  do |f|%>
        <%= f.input :address, label: "Adresse", placeholder: 'Où jouer ?', required: false%>
        <%= f.input :capacity, label: "Artistes", input_html: { min: 1 }, placeholder: 'Ajouter', as: :numeric, required: false%>
        <%= f.input :item, label: "Instrument", collection: Item.all.map{|s| s.name}, wrapper_html: { class: 'choose-instrument' }, prompt: "Sélectionner", required: false %>
        <%= f.submit "Rechercher", class: 'btn btn-primary mt-4' %>
      <% end %>
    </div>
    <div class="tags-filter">
      <% @tags.each do |tag|%>
        <div class="tag-filter">
          <%= tag %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
  <div class="cards-rooms">
  <% i = 0%>
    <% @rooms.each do |room| %>
        <div class="card-room card-room-index <%="card#{i}"%>">
          <%= link_to new_room_booking_path(room, Date.today) do  %>
             <%= cl_image_tag room.photo.key, class: "card-studio-img" %>
          <% end %>
          <div class="card-room-infos">
            <div class="studio-name">
             <p><%= room.studio.name %></p>
            </div>
            <div class="card-room-description">
              <h2><%= link_to room.name, new_room_booking_path(room, Date.today) %></h2>
              <p class="address"><%= room.studio.address %></p>
              <p class="description mt-2"><%= room.description %></p>
              <p class="mt-2 capacity">  <i class="fas fa-users"></i> <%= room.capacity %> </p>
            </div>
            <div class="card-room-gears d-flex mt-2">
              <div class="d-flex">
                Matériel
                <a class="ml-2" data-toggle="collapse" href="#collapseExample-<%=room.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
                  <i class="fas fa-plus"></i>
                </a>
              </div>
              <div class="btn btn-primary btn-musicnow">
                <%= link_to "Réserver", new_room_booking_path(room, Date.today) %>
              </div>
            </div>
            <div class="collapse" id="collapseExample-<%=room.id%>">
              <% room.items.each do |item| %>
                <p>- <%= item.name %></p>
              <% end %>
            </div>
          </div>
        </div>
      <% i = i + 1 %>
    <% end %>
  </div>
</div>